allowBuilds:
  lefthook: true
  nx: false
  unrs-resolver: true
catalog:
  "@storm-software/config": ^1.138.10
  "@storm-software/config-tools": ^1.190.73
  "@storm-software/cspell": ^0.46.141
  "@storm-software/eslint": ^0.170.106
  "@storm-software/git-tools": ^2.131.80
  "@storm-software/linting-tools": ^1.134.3
  "@storm-software/markdownlint": ^0.30.229
  "@storm-software/pnpm-tools": ^0.7.84
  "@storm-software/prettier": ^0.59.126
  "@storm-software/tsconfig": ^0.48.140
  unrs-resolver: ^1.12.2
  zx: ^8.8.5
  prettier: ^3.8.4
  rimraf: ^6.1.3
  lefthook: ^1.13.6
  eslint: ^10.5.0
  copyfiles: ^2.4.1
shamefullyHoist: true
engineStrict: true
fetchTimeout: 240000
dedupeDirectDeps: true
dedupePeerDependents: true
cleanupUnusedCatalogs: true
